# docker/docker-compose.yml
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: baby_tracker_db
    environment:
      POSTGRES_DB: baby_tracker
      POSTGRES_USER: baby_user
      POSTGRES_PASSWORD: baby_password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U baby_user -d baby_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # pgAdmin (Interface gráfica - opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: baby_tracker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@baby-tracker.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: